import { Species } from "./Species";
import { SpatialGrid } from "./SpatialGrid";
import { HabitatAreaPopulation } from "./HabitatAreaPopulation";
import { SpatialGridCell } from "./SpatialGridCell";
import { AnalysisResult } from "./AnalysisResult";
import { VulnerabilityResult } from "./VulnerabilityResult";
export type HabitatArea = {
  id: number;
  name: string | null;
  species: Species | null;
  spatial_grid: SpatialGrid | null;
  density_per_precense: number | null;
  habitat_area_population: HabitatAreaPopulation | null;
  area: number | null;
  bbox_left: number | null;
  bbox_top: number | null;
  bbox_right: number | null;
  bbox_bottom: number | null;
  polygon: object | null;
  spatial_grid_cells: SpatialGridCell[] | null;
  analysis_result: AnalysisResult | null;
  meta: object | null;
  vulnerability_result: VulnerabilityResult | null;
  dont_expires: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
  publishedAt: string | null;
  createdBy: any | null;
  updatedBy: any | null;
  localizations: HabitatArea[] | null;
  locale: string | null;
};
