import { Species } from "./Species";
import { MapSpatialGrid } from "./MapSpatialGrid";
import { MapSpatialGridCell } from "./MapSpatialGridCell";
export type MapHabitatArea = {
  id: number;
  name: string | null;
  species: Species | null;
  map_spatial_grid: MapSpatialGrid | null;
  area: number | null;
  indexed: boolean | null;
  bbox_left: number | null;
  bbox_top: number | null;
  bbox_right: number | null;
  bbox_bottom: number | null;
  polygon: object | null;
  points: object | null;
  points_count: number | null;
  map_spatial_grid_cells: MapSpatialGridCell[] | null;
  meta: object | null;
  months_densities: object | null;
  months_presence_old: object | null;
  months_presence_new: object | null;
  old_per_point: number | null;
  new_per_point: number | null;
  old_flight_percent: number | null;
  new_flight_percent: number | null;
  buffer_around_point: number | null;
  comments: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  publishedAt: string | null;
  createdBy: any | null;
  updatedBy: any | null;
  localizations: MapHabitatArea[] | null;
  locale: string | null;
};
