import { MapSpatialGrid } from "./MapSpatialGrid";
import { Result } from "./Result";
import { Species_SpeciesAreaInfo__component } from "./Species_SpeciesAreaInfo__component";
import { MapHabitatArea } from "./MapHabitatArea";
import { MapImportConfig } from "./MapImportConfig";
import { SensitiveArea } from "./SensitiveArea";
import { MapSpatialGridDistrict } from "./MapSpatialGridDistrict";
import { MapVulnerabilityResult } from "./MapVulnerabilityResult";
import { MapSpeciesMigration } from "./MapSpeciesMigration";
export type MapSpatialGridCell = {
  id: number;
  spatial_grid: MapSpatialGrid | null;
  bbox_left: number | null;
  bbox_top: number | null;
  bbox_right: number | null;
  bbox_bottom: number | null;
  polygon: object | null;
  results: Result[] | null;
  total_vulnerability: number | null;
  species_infos: Species_SpeciesAreaInfo__component[] | null;
  habitat_areas: MapHabitatArea[] | null;
  import_configs: MapImportConfig[] | null;
  sensitive_areas: SensitiveArea[] | null;
  map_spatial_grid_district: MapSpatialGridDistrict[] | null;
  map_vulnerability_results: MapVulnerabilityResult[] | null;
  map_species_migrations: MapSpeciesMigration[] | null;
  createdAt: string | null;
  updatedAt: string | null;
  createdBy: any | null;
  updatedBy: any | null;
};
