import { SpatialGrid } from "./SpatialGrid";
import { Result } from "./Result";
import { Species_SpeciesAreaInfo__component } from "./Species_SpeciesAreaInfo__component";
import { HabitatArea } from "./HabitatArea";
import { SpeciesCellPopulation } from "./SpeciesCellPopulation";
import { SensitiveArea } from "./SensitiveArea";
import { SpatialGridDistrict } from "./SpatialGridDistrict";
import { VulnerabilityResult } from "./VulnerabilityResult";
export type SpatialGridCell = {
  id: number;
  spatial_grid: SpatialGrid | null;
  bbox_left: number | null;
  bbox_top: number | null;
  bbox_right: number | null;
  bbox_bottom: number | null;
  polygon: object | null;
  results: Result[] | null;
  total_vulnerability: number | null;
  species_infos: Species_SpeciesAreaInfo__component[] | null;
  habitat_areas: HabitatArea[] | null;
  species_cell_populations: SpeciesCellPopulation[] | null;
  sensitive_areas: SensitiveArea[] | null;
  spatial_grid_district: SpatialGridDistrict | null;
  vulnerability_results: VulnerabilityResult[] | null;
  createdAt: string | null;
  updatedAt: string | null;
  publishedAt: string | null;
  createdBy: any | null;
  updatedBy: any | null;
};
