entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: example@mail.ru
      storage: acme.json
      httpChallenge:
        entryPoint: web
